### ISSUE TITLE
minimap preCluster

### ISSUE THREAD

**Issue by yangtried** [Magdoll/Cogent#12]
hi ,
    I am delighted to use minimap for preprocessing when using large data. However, the number of transcripts in the different partition is unbalanced, with one of them reaching tens of thousands, resulting in a very slow division and memery costing of the gene family.I would like to know there are no parameters to solve this problem or other methods，Looking forward to your reply，thanks.

yang

**Comment by Magdoll** [comment]
Hi,
Yes I am aware of this issue and trying to improve it. Note that the imbalance is also somewhat natural --- some bins (transcripts) are simply more abundant! But it does look like right now the preclustering processing is a bit too relaxed, sometimes binning not-so-related sequences together.

I encourage you to update to the latest version of Cupcake (v.3.9 https://github.com/Magdoll/cDNA_Cupcake/tree/v3.9) and try the `--dun_use_partial` option. 

-Liz

**Comment by yangtried** [comment]
@Magdoll Thank you very much for your reply and expect you to improve this problem and I will try the new version of Cupcake

**Comment by yangtried** [comment]
@Magdoll Hello, I have installed the latest version of cupcake, but can not function properly. Have you ever tried to run this version and the unbalanced partition has not been improved? I am very anxious to deal with this problem, whether you can change a parameter to control the problem?

**Comment by Magdoll** [comment]
Hi @yangtried ,
Do you mean you tried `--dun_use_partial` and the preclustering results remain the same? Or just that it didn't improve the largest partitions any better. I would need more details on the largest precluster bin sizes to have some idea.

--Liz

**Comment by yangtried** [comment]
hi @Magdoll ，
 I did not run the latest version of cupcake smoothly because of the following error:
“ pkg_resources.run_script('cupcake==3.9', 'run_preCluster.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 739, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1500, in run_script
  File "/ifs/TJPROJ3/PB/yangjie/cogentlib/Python2/lib/python2.7/site-packages/cupcake-3.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/run_preCluster.py", line 182, in <module>
    main(args.cpus, args.dun_make_bins, args.dun_use_partial)
TypeError: main() takes at most 2 arguments (3 given)”

**Comment by yangtried** [comment]
Hi @Magdoll ，
 I did not run the latest version of cupcake smoothly because of the following error:
“ File "/Python2/bin/run_preCluster.py", line 5, in <module>
    pkg_resources.run_script('cupcake==3.9', 'run_preCluster.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 739, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1500, in run_script
  File "/Python2/lib/python2.7/site-packages/cupcake-3.9-py2.7-linux-x86_64.egg/EGG-INFO/scripts/run_preCluster.py", line 182, in <module>
    main(args.cpus, args.dun_make_bins, args.dun_use_partial)
TypeError: main() takes at most 2 arguments (3 given)”

**Comment by Magdoll** [comment]
Hi,

There was an issue with v3.9 when I merged two branches. It should be corrected now in the v4.0 version: https://github.com/Magdoll/cDNA_Cupcake/tree/v4.0

Here's a comparison of the top 5 bins by using and not using `--dun_use_partial`:

### using `--dun_use_partial`
```
cluster   size
5234    907
5060    845
3117    807
5094    749
3976    618
```

### not using `--dun_use_partial`

```
cluster   size
7124    6570
4658    988
7123    974
4472    808
3637    525
```

**Comment by yangtried** [comment]
hi @Magdoll ，
 I have used the 4.0 version, and there is a big improvement in partition balancing, but unlike your top 5 bins, there are still thousands of transcripts that form a partition. I have a different question, why do some transcripts can form a gene family, and some are classified as unassigned? Looking forward to your reply ~

**Comment by Magdoll** [comment]
Hi @yangtried ,

I tested the `--dun_use_partial` option on a very small dataset (65k FLNC sequences), so naturally, my top bins are still very small. Having a few thousand in a partition is still going to run decently fast.

> why do some transcripts can form a gene family, and some are classified as unassigned?


the preClustering step classifies all sequences that do not have any hits (if you use `--dun_use_partial`, it would have to be a full hit) to any other sequence, based on minimap results. This means these sequences are *orphans* and they get put in the file `preCluster_out.orphans.fasta` and will have the stat as `orphan` in the output CSV file `preCluster.output.csv`. Additionally, preClustering also identifies possible PCR chimeras and put them in the file `preCluster_out.chimeras.fasta`, marking them as `chimera` in the output CSV. 

Let me know if you have more questions.
--Liz

**Comment by yangtried** [comment]
hi @Magdoll ，
Thank you very much for your reply, I use the 330M full length transcript, use --dun_use_partial get about 10,000 bins, each bin contains about 3 to 10 transcripts, only one bin contains 2000 transcripts, I do not know Is this normal? Another question, when refactoring, I get a very short contig, as shown below, path1.why is this happening? I think this contig is not desirable.
“>path0
TCCTCCATAGCCGCC.........
>path1
GATCTTGT"

**Comment by Magdoll** [comment]
Hi @yangtried ,

1. It really depends on the diversity and abundance distribution of your transcripts in the sample, so I can't comment on that. minimap is pretty promiscuous, so if it truly can't find more than 3-10 sequences that have decent (full hits, because you used `--dun_use_partial`), then it is what it is.

2.  The short "path1" will occasionally happen with heavily trimmed sequences. Cogent by default trims away all lower case bases at the beginning and end of each sequence in `in.fa`. So take a look at that bin at the `in.trimmed.fa`. Is there one that is heavily trimmed?

--Liz

**Comment by yangtried** [comment]
hi @Magdoll ，
Thank you very much for your reply. Does it seem normal to have an over-pruning sequence in in.trimmed.fa?
You have already replied to how the orphan was formed, I am very sorry I did not understand what is the meaning of hit here. Can you explain it for me? Why do you think that the sequence containing more than 16 PolyTs in the first 20 bases of an orphan sequence is a PCR chimeric sequence? Looking forward to your reply.

**Comment by Magdoll** [comment]
Hi @yangtried ,
For short sequences (< 500 bp) that have a lot of lower case, i.e. indication of low quality, bases at the flanking regions, trimming them away would lead to a very short sequence that is of little use to the Cogent reconstruction process. If you think the lower case sequences are actually trustworthy and should not be trimmed, you can provide an input sequence that is all upper case. Otherwise, Cogent prefers not to deal with low-quality bases.

In terms of whether that's "normal", I guess the answer is I have certainly seen that happen with Iso-Seq data, but not that often.

re: orphan and chimeras --- a "hit" in the preclustering step means a sequence (from `isoseq_flnc.fasta`) must have at least one alignment record with another sequence based on the minimap result. Minimap is very sensitive, capable of detecting sequence similarities at as low as 20-30%. So, if a sequence has no hits, then it is an "orphan", and will be thrown out in the preclustering step. Further, sequences that have more than 16 poly Ts in the first 20 bases have a very high chance of being a PCR chimera, because it indicates a structure that is:


cDNA primer --- TTTTTTTT --- part of transcript1 --- part of transcript 2 --- AAAAAAA --- cDNA primer. 

For a graphical representation, see [this wiki on different kinds of artifacts](https://github.com/PacificBiosciences/cDNA_primer/wiki/Artificial-concatemers,-PCR-chimeras,-and-fusion-genes#pcr). 


--Liz

**Comment by yangtried** [comment]
hi @Magdoll ，
Hi, after testing, I also found a problem that when using the argument, --unun_partial, the orphan sequence increased, as I got 7743 orphan sequences and 1522 chimeric sequences before using this parameter, however, after using the parameters , The same test data, I got 64559 orphan sequences and 11251 chimeric sequences, and these sequences in the subsequent gene family and reconstruction process is no longer used, this will lose a lot of data, is that reasonable?

**Comment by Magdoll** [comment]
Hi @yangtried ,

Yes it is totally expected that using `--dun_use_partial` would increase the number of orphan sequences. Because `--dun_use_partial` means any sequence that only has a partial hit will now be considered not a hit and is more likely to become "orphans".

--Liz
