### ISSUE TITLE
collapsing problem

### ISSUE THREAD

**Issue by whispersbowl** [Magdoll/Cogent#16]
Hi, 
I am running Cogent and when running the command:

process_kmer_to_graph.py my_high_qual_isoforms.fa my_high_qual_isoforms.fa.s1000k30.dist CP1/ CP1

It gives me the error:
AttributeError: 'Graph' object has no attribute 'nodes_iter'

which seems to be a compatibility error between the code and the NetworkX new version, or maybe not; either way, I am stuck, can you help me please?.

this is the full output:

making weight graph from  CP1-high_qual_isoforms.fa.s1000k30.dist
graph contains 5974 nodes, 188873 edges
performing ncut on graph....
Traceback (most recent call last):
  File "/home/calla2/anaconda2/envs/anaCogent/bin/process_kmer_to_graph.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==2.1', 'process_kmer_to_graph.py')
  File "/home/calla2/anaconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/calla2/anaconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/home/calla2/anaconda2/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 155, in <module>
    ncut_threshold=args.ncut_threshold)
  File "/home/calla2/anaconda2/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 77, in family_finding
    run_ncut(g, labels2_map, ncut_map, nodelist, ncut_threshold)
  File "/home/calla2/anaconda2/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/process_kmer_to_graph.py", line 17, in run_ncut
    labels = np.array([i for i in G.nodes_iter()])
AttributeError: 'Graph' object has no attribute 'nodes_iter'

THANKS!

**Comment by Magdoll** [comment]
Hi @whispersbowl ,

Can you check your networkx version? see below:

```
import Python 2.7.10 (default, Sep 22 2017, 12:11:41) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
networkx.__version__
>>> networkx.__version__
'1.9.1'
```

**Comment by whispersbowl** [comment]
Hi @Magdoll 

I have checked and it is version 2.0. Networkx got installed within my anaCogent environment. Do you think is advisable to downgrade?.

**Comment by Magdoll** [comment]
@whispersbowl ,
It seems like `nodes_iter` was removed in version 2.0.

See in version 1.9, `nodes_iter` is described under the Nodes section:
https://networkx.github.io/documentation/networkx-1.9/reference/functions.html#graph

It appears in version 2.0 the function is now called `nodes` under the Nodes section:
https://networkx.github.io/documentation/stable/reference/functions.html

I'll file a bug/issue to make note of this. I'll probably write something in the code to handle both 1.9 and 2.0 cases (since I imagine many may still be using 1.9).

Anaconda can handle downgrades (see [here](https://stackoverflow.com/questions/23974217/how-do-i-revert-to-a-previous-package-in-anaconda)), if this becomes an issue, let me know and I'll put in the fix sooner than later. I don't want to immediately upgrade to 2.0 since I think there may be other changes required.

--Liz

**Comment by whispersbowl** [comment]
thanks!

Just reporting, so far I had no problems running process_kmer_to_graph.py and a couple of other steps in the environment after downgrading the to networkx 1.9.1.
