### ISSUE TITLE
Is it possible to get AS events by Cogent?

### ISSUE THREAD

**Issue by raechin** [Magdoll/Cogent#2]
Dear Cogent developer,

I'm looking for a tool that can detect AS event from PACbio full length transcripts without reference genome. It is exciting that Cogent seems can. As described in Fig1 in the manuscript, Cogent can recontruct the contig for each gene. 

Is it possible to get different AS events (exon skipping, intron retention, etc.) from the reconstructed contigs? Some tools like Astalavista needs a gtf file to get different AS events. Will Cogent output some gff file that describes exon-intron structures for the contigs? 

Or is there other way to determine the AS event for each isoform of a reconstructed contig? 

Thank you very much!

W.

**Comment by Magdoll** [comment]
Hi @raechin ,

Yes, theoretically you can get AS events using the Cogent reconstructed "contigs" as a "fake genome", with a caveat --- that is, Cogent reconstruction doesn't always generate exactly one contig. Sometimes it will generate multiple contigs if it cannot resolve the order of some AS events.

ex: 
Isoform A:  exon 1, 2, 3
Isoform B:  exon     2, 3
Isoform C: exon   1,    3,  4

In this case, Cogent can infer the order of exons to be 1 --> 2 --> 3 --> 4 and make one contig. The output contig is called "cogent2.fa" for that gene family and you can map (using GMAP or STAR) the input (which is `in.trimmed.fa` with lower case flanking bases trimmed off) to `cogent2.fa` and get the AS events. GMAP will be able to produce GTF files (or at least GFF) as well as SAM/BAM.

In another case:
Isoform A:  exon 1, 2, 3
Isoform B:  exon 1, 2, 4

There is insufficient information regarding the order of 3 and 4. So, Cogent will output two contigs to `cogent2.fa` and each of the two isoforms will map to only one of them. In this case, we can tell that A and B must be two different isoforms (since they map to two diff contigs), and most likely, the difference comes from AS, but we cannot determine the order of that difference. 

Hope this makes sense.

If you want to squeeze as much out of the Cogent result for AS, you could run Cogent and only use the families that have exactly one contig in `cogent2.fa`. For the others with more than one contig, you may have to come up with some other way of determining AS.

--Liz

**Comment by raechin** [comment]
Thank you very much for your quick and detailed response, Liz! I'll go trying Cogent for my pacbio data. Hopefully it'll work!

W.

**Comment by yangtried** [comment]
Dear Cogent developer,
I have got "cogent2.fa" and "in.trimmed.fa.cogent2.gff" files,but I want to know how to find AS events,I don't know how to do use gff file,could you give me some advices?
Thank you very much!
Yh

**Comment by Magdoll** [comment]
Hi @yangtried ,

In the absence of a genome, you can  use `cogent2.fa` as a fake genome. Then you can visualize the input mapped to the fake genome which is the GFF file `in.trimmed.fa.cogent2.gff`. 

<img width="696" alt="screenshot 2017-08-31 09 55 25" src="https://user-images.githubusercontent.com/590447/29935132-94789c34-8e32-11e7-84ec-84c6f0ffc8d0.png">


Here is an example of how Cogent visualizes AS events. Note that the Cogent-based view (top, blue) does not show any introns that are universally spliced out.

**Comment by NElight** [comment]
hi, dear Cogent developer:
i use ex:
Isoform A: exon 1, 2, 3
Isoform B: exon 2, 3
Isoform C: exon 1, 3, 4
but this three fasta can not result in one family, how can i get the 1,2,3,4 result?
thank u

**Comment by Magdoll** [comment]
@NElight ,
I'm not sure I understand. Are you running reconstruction? How many sequences do you have in the input (in.trimmed.fa) and how many reconstructed contigs (in cogent2.fa) did you get? How do you know you have the isoform A-B-C structure as described?

--Liz

**Comment by abeyeu** [comment]
@Magdoll
I am carrying on a population genetics work.
Data: high-quality full-length transcriptome sequences of one sample and NGS transcriptome of many samples (PE150).
I would use spliced aligners (STAR ) map NGS data to cogent2.fa and then follow GATK protocol to call variants in NGS data. Is it makes sense?
Thanks very much！
abeyeu

**Comment by Magdoll** [comment]
Hi @abeyeu ,
Yes you can use `cogent2.fa` as a fake genome to map data and call GATK.

--Liz
