### ISSUE TITLE
Confusion about collapsing result with Cogent

### ISSUE THREAD

**Issue by fantastycrane** [Magdoll/Cogent#22]
Hi @Magdoll ,
I have run Cogent according to the tutorial and collapsed original sequences with fake genome created by Cogent. I noticed that considerable part of sequences , about 20% in my case, were classified to ignored_ids. Is this normal? Shouldn't it be that all sequence can map (parameters: -c 0.95, -i 0.85) to the fake genome based on them? And should I exclude these ignored sequences or combine them with collapsed result?

**Comment by Magdoll** [comment]
Hi @fantastycrane ,

Can you look into whether the thrown out sequences were unmapped or removed due to low coverage/identity?

You can use commands below:
```
grep -c "Unmapped" xxxx.ignored_ids.txt
grep -c "Identity" xxx.ignored_ids.txt
grep -c "Coverage" xxx.ignored_ids.txt
```

Unmapped reads could be because they were excluded during the Cogent family finding phase (they would be part of the `unassigned` in the output). Low coverage or identity reads have other explanations. I'd like to see which category is the most dominant first before diving into details.

--Liz

**Comment by fantastycrane** [comment]
Most of them are unmapped (5565, 112 and 1980 for unmapped, low identity and low coverage). There are 4373 unassigned sequences and I have concatenated unassigned with Cogent contigs while creating the "fake genome".

**Comment by Magdoll** [comment]
Hi @fantastycrane ,

The low coverage ones are probably thrown out because the Cogent reconstruction trims of low quality (lower case) bases at the ends (`in.fa` --> `in.trimmed.fa`) so the reconstruction contigs would not include the flanking bases. If you can take a look at the message for `<seqid> Coverage 0.93 is too low.` then that probably explains it.

For the unmapped, can you trace where those unmapped come from? If you have included the unassigned sequences, they should be included.

**Comment by fantastycrane** [comment]
Most of unmapped sequences are found in preCluster_out.orphans.fasta and preCluster_out.chimeras.fasta. Should these sequences be included while creating fake genome?

**Comment by Magdoll** [comment]
Hi @fantastycrane ,

Oh that makes sense now!

The `preCluster_out.orphans.fasta` are orphan sequences that are effectively "unassigned", so yes they should be included. I'll update the wiki.

The `preCluster_out.chimeras.fasta` are likely chimeric artifacts. I recommend simply discarding them.

--Liz

**Comment by fantastycrane** [comment]
OK, thanks.
