### ISSUE TITLE
interpreting the results

### ISSUE THREAD

**Issue by ale07alvarez** [Magdoll/Cogent#54]
Is there additional documentation for interpreting the results of this pipeline?

**Comment by ale07alvarez** [comment]
ref_sequence1   3326_0|path291
For this particular gene family there are multiple paths what is the meaning a path within a gene family?

And from the annotation files what is the difference between a PacBio transcript and an exon?

3326_0|path254  PacBio  transcript      144     6064    .       +       .       gene_id "xx.2068"; transcript_id "xx.2068.1";
3326_0|path254  PacBio  exon    144     634     .       +       .       gene_id "xx.2068"; transcript_id "xx.2068.1";

**Comment by Magdoll** [comment]
Hi @ale07alvarez ,

Sorry for the late response.

You are showing snippets of a GFF file. Each "transcript" could consist of multiple "exons", so that is what you're seeing here. A GFF record would start with a "transcript" record followed by one or more lines of "exons", and you can tell it's talking about the same transcript if the `transcript_id` is the same.

Does that answer your question?

--Liz
