### ISSUE TITLE
process_kmer_to_graph.py generating partitions of size 1

### ISSUE THREAD

**Issue by goodgodric28** [Magdoll/Cogent#62]
I ran `run_mash.py -k 30 --cpus 10 demux_tsujii_2cells.polished.hq.fasta` and `process_kmer_to_graph.py --sim_threshold 0.10 demux_tsujii_2cells.polished.hq.fasta demux_tsujii_2cells.polished.hq.fasta.s1000k30.dist tsujii_2cells_0.9 tsujii_0.9`, and when I look at the partition file, I get multiple partitions of size 1 

> tsujii_19       1       transcript/8986

Is there a particular reason these are not included in the unassigned bin during this process? Do I need to modify the parameters? These are failing in the reconstruction phase, which makes sense.

**Comment by Magdoll** [comment]
HI @goodgodric28 ,

Because of the way the graph is partitioned, sometimes there will be singletons. This means that these sequences *do* have some, but probably very few/weak sequence similarity to other sequences and the graph cutting (gene-family finding) algorithm decides to cut it out as a singleton cluster.

And yes these would fail the reconstruction phase. I should really put them as "unassigned". I'll note that down for the future.

Hope this answers the question!


--Liz
