### ISSUE TITLE
bx-python error when install Cogent

### ISSUE THREAD

**Issue by shenli-js** [Magdoll/Cogent#82]
Hi ,Magdoll !
When I install cogent ，conda env allways changed python3.7 to python2.7. It happened when running `conda install -n anaCogent -c bcbio bx-python`. I searched bx-python by conda search，it shows：
```
# Name                       Version           Build  Channel             
bx-python                      0.7.2      np18py27_0  bcbio               
bx-python                      0.7.2      np18py27_1  bcbio               
bx-python                      0.7.2      np19py27_2  bcbio               
bx-python                      0.7.3      np19py27_0  bcbio               
```
In channel bcbio, bx-python was built by python2.7 , so I can't install it with python3.7.
Is there anything wrong with me?

**Comment by LionOfComarre** [comment]
Encountered a similar issue when trying to install. Got a solving environment error from conda since the bcbio version of bx-python is built on 2.7 and the environment is specified to be 3.7. The bioconda version of bx-python requires python 3.8 or 3.9. You'd either have to find a channel supplying the right version of bx-python, or change the version of the environment, but that might break other dependencies.
